repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy type check
        entry: bash -c 'cd python && mypy .'
        language: system
        files: ^python/.*\.py$
        pass_filenames: false
      - id: smoke-tests
        name: smoke tests
        entry: bash -c 'cd python && pytest -m smoke'
        language: system
        files: ^python/.*\.py$
        pass_filenames: false
