# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/saltstack/mirrors-nox
    rev: 'v2022.11.21'  # Use the sha / tag you want to point at
    hooks:
      - id: nox
        files: ^/.*\.py$
        args:
          - -f
          - python/noxfile.py
          - --
